project:
  type: website
  output-dir: docs
  
website:
  title: "Empirical Identifiability"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - ecls-k.qmd
      - proposal.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



