---
title: "Empirical Identifiability MLM Writeup"
author: "Jess Helmer"
date: last-modified
format: 
  html:
    toc: true
    toc-location: left
    html-table-processing: none
    html-math-method: mathjax
    toc-depth: 4
execute:
  echo: false
---

```{r reading}
#| message: false
library(tidyverse)
library(targets)
library(patchwork)
library(ggtext)
library(gt)

tar_source(here::here("Scripts", "R"))

tar_load(
  c(
    ecls_dat, full_and_subset_sample_sizes, #n_boostraps,
    param_set, params,
    full_data_models
  ),
  store = here::here("_targets")
)

ecls_full <- full_and_subset_sample_sizes |>
  filter(data_type == "full")
ecls_subset <- full_and_subset_sample_sizes |>
  filter(data_type == "full")
```

Using bootstrapping as a method to diagnose poor empirical identifiability is not limited to the explicit factor analysis framework. We now present an example of this technique successfully showing when a multilevel model has reached a complexity level where the variability in the data is not sufficient to provide an identified solution. To do this, we manipulated the sample size of a dataset as a proxy for whether or not the data was likely to be well-identified, and examined the distributions of bootstrapped parameter estimates for multilevel models of increasing complexity.

## Background

### Multilevel Models

$$
x = y + z
$$

## Methods

To examine the effectiveness of bootstrapping as a method of identifying poor identifiability with multilevel models, we manipulated the sample size of a dataset as a proxy for whether or not the data was likely to be well-identified, and examined the distributions of bootstrapped parameter estimates for multilevel models of increasing complexity.

### Data

For this study, we used a large publicly available dataset with a multilevel structure, the Early Childhood Longitudinal Studies Program's data from kindergartners in 2011 (ECLS-K). This full dataset contains information on students' test scores in various subjects along with many student-, classroom-, and school-level variables for `r format(ecls_full$n_students, big.mark = ",")` students in `r format(ecls_full$n_schools, big.mark = ",")` schools, creating `r format(ecls_full$n_observations, big.mark = ",")` observations total. We accessed this data through the `{edsurvey}` R package. 

### Model

As a hypothetical model of interest, we can examine the effect of student SES and schools being public or private with a two-level multilevel model with a cross-level interaction and random slopes, providing information about the population effects of student socioeconomic status and public vs. private schools on student math achievement scores as well as the variation of the effect of student SES across schools. SES was a continuous variable constructed by the ECLS-K research team, and we dummy-coded public vs. private schools with an indicator for the school type being private.

To understand how the bootstrapping procedure functions as a diagnostic tool with increasing model complexity, we fit a series of simpler models building towards the full model of interest. We first fit the unconditional model, 

$$
\begin{aligned}
  \text{Level 1}: & \quad \text{MATH SCORE}_{ij} = \beta_{0j} + r_i \\[.8em]
  \text{Level 2}: & \quad \vcenter{\begin{array}{l}
      \beta_{0j} = \gamma_{00} + u_{0j} \\
    \end{array}} \\[1.6em]
  \text{MATH SCORE}_{ij} &= \gamma_{00} + u_{0j} + r_i
\end{aligned}
$$

, then added student SES as a student-level predictor, 

$$
\begin{aligned}
  \text{Level 1}: & \quad \text{MATH SCORE}_{ij} = \beta_{0j} + \beta_{1j}\text{SES}_i + r_i \\[.8em]
  \text{Level 2}: & \quad \vcenter{\begin{array}{l}
      \beta_{0j} = \gamma_{00} + u_{0j} \\
      \beta_{1j} = \gamma_{10}
    \end{array}} \\[1.6em]
  \text{MATH SCORE}_{ij} &= \gamma_{00} + \gamma_{10}\text{SES}_i + u_{0j} + r_i
\end{aligned}
$$

, then added  as a school-level predictor,
$$
\begin{aligned}
  \text{Level 1}: & \quad \text{MATH SCORE}_{ij} = \beta_{0j} + \beta_{1j}\text{SES}_i + r_i \\[.8em]
  \text{Level 2}: & \quad \vcenter{\begin{array}{l}
      \beta_{0j} = \gamma_{00} + \gamma_{01}\text{PRIVATE}_j + u_{0j} \\
      \beta_{1j} = \gamma_{10}
    \end{array}} \\[1.6em]
  \text{MATH SCORE}_{ij} &= \gamma_{00} +  \gamma_{10} \text{SES}_i + \gamma_{01} \text{PRIVATE}_j + u_{0j} + r_i
\end{aligned}
$$

, then interacted SES and private for a cross-level interaction,

$$
\begin{aligned}
  \text{Level 1}: & \quad \text{MATH SCORE}_{ij} = \beta_{0j} + \beta_{1j}\text{SES}_i + r_i \\[.8em]
  \text{Level 2}: & \quad \vcenter{\begin{array}{l}
      \beta_{0j} = \gamma_{00} + \gamma_{01}\text{PRIVATE}_j + u_{0j} \\
      \beta_{1j} = \gamma_{10} + \gamma_{11}\text{PRIVATE}_j
    \end{array}} \\[1.6em]
  \text{MATH SCORE}_{ij} &= \gamma_{00} + (\gamma_{10} + \gamma_{11} \text{PRIVATE}_j) \text{SES}_i + \gamma_{01}\text{PRIVATE}_j + u_{0j} + r_i
\end{aligned}
$$

, and finally added random slopes on the effect of student gender to allow for variation across schools, 

$$
\begin{aligned}
  \text{Level 1}: & \quad \text{MATH SCORE}_{ij} = \beta_{0j} + \beta_{1j}\text{SES}_i + r_i \\[.8em]
  \text{Level 2}: & \quad \vcenter{\begin{array}{l}
      \beta_{0j} = \gamma_{00} + \gamma_{01}\text{PRIVATE}_j + u_{0j} \\
      \beta_{1j} = \gamma_{10} + \gamma_{11}\text{PRIVATE}_j  + u_{1j}
    \end{array}} \\[1.6em]
  \text{MATH SCORE}_{ij} &= \gamma_{00} + (\gamma_{10} + \gamma_{11} \text{PRIVATE}_j  + u_{1j}) \text{SES}_i + \gamma_{01}\text{PRIVATE}_j + u_{0j} + r_i
\end{aligned}
$$

We used the `{lme4}` R package to fit these models.

### Conditions

#### Manipulating Identifiability

Because this dataset is so large, we assume that the model fit on the full dataset is well-identified. We can then manipulate identifiability by randomly subsetting the data into smaller datasets. This represents what smaller research teams might be more likely to encounter in their work. We had two crossed sample size conditions: number of schools (10 or 30) and number of students within schools (3 or 10). We chose these conditions to roughly mimic potential real-world sample sizes that at the low end, may likely will not contain enough variability to identify the model and at the high end, will contain enough variability to identify the model.

#### Bootstrapping Conditions

Literature on bootstrapping analysis discusses two broader methods of bootstrapping: parametric and non-parametric bootstrapping. Parametric bootstrapping involves fitting a model to data, and then using the parameter estimates from the model as a basis to simulate further data from the model. Given that our intention with this bootstrapping is to examine differences in parameter estimates throughout perturbations of the data, and not the theoretical sampling distribution of parameters *given* the model, we do not use parametric bootstrapping in this study.

Non-parametric bootstrapping is the perhaps more familiar kind, where observations are randomly sampled from the data with replacement to create new, slightly different, versions of the observed data. For a multilevel model, this kind of bootstrapping is more complex than for a single-level model, because the clustering adds additional complexity as to which level of observation from which to sample bootstraps. The literature on bootstrapping for multilevel models provides support for both cluster-level bootstrapping, randomly sampling clusters from the data with replacement, as well as (in the case of a two-level model) two-stage bootstrapping, first sampling clusters, and then sampling observations within cluster. Simply randomly sampling observations at the lower level is not recommended, given that it does not preserve the clustered structure of the data. However, given that none of these bootstrapping types have been evaluated for their performance as an identifiability diagnostic method, we include all three of these methods in our study: two-stage, cluster, and single-level bootstrapping. 

### Procedure 

We subsetted the full ECLS-K dataset to include just the variables of interest for this study (student math achievement, student SES, and school type (public vs. private), and we removed any observations with missing data. We also removed any schools with fewer than ten students, such that all schools in the dataset would be able to accommodate the maximum students-per-school condition. The remaining data contained `r format(ecls_subset$n_students, big.mark = ",")` students, `r format(ecls_subset$n_schools, big.mark = ",")` schools, for `r format(ecls_subset$n_observations, big.mark = ",")`. All analysis was conducted on this data subset.

We conducted `[n]` replications for each combination of conditions in this study. For each replication, we randomly sampled a four smaller subsets of the data with $N_{schools}$ schools and $N_{students per school}$, one for each of the combinatiosn 

For each data subset, we created `n_boostraps` bootstraps of each dataset. 

### Outcomes

Our outcome of interest was the bootstrapped sampling distribution for each parameter; specifically, the shape of each distribution and the correlations of the sampling distributions between pairs of parameters. We also tracked warning and error messages from the `{lme4}` package. 


## Results




















